name: Check broken links

on: [page_build, workflow_dispatch]

jobs:
  broken-link-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: ruzickap/action-my-broken-link-checker@v2
        with:
          url: https://face-clinic.pl
          cmd_params: "--exclude cloudflare --exclude instagram --exclude cdn-cgi --max-connections=3 --color=always"
